offset: 0
name: USART_0
consumer: "master"
baud_rate: 115200
data_bits: 8
stop_bits: 1
parity: "none"
flow_control: "none"
fifo_depth: 64
synchronous_mode: "true"
clock_polarity: "low"
clock_phase: "first"
clock_rate: 16000000
buffer: "0000000000"
